apiVersion: v1
kind: Service
metadata:
  name: message-broker-service
  labels:
    name: message-broker-service-nodeport
    app: bale-app
spec:
  type: NodePort
  selector:
    name: message-broker-pod
    app: bale-app
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
    nodePort: 30000
  - name: http
    port: 2112
    targetPort: 2112
    nodePort: 30001

