apiVersion: v1
kind: Service
metadata:
  name: fileserver
  labels:
    name: fileserver-service-clusterip
    app: bale-app
spec:
  type: ClusterIP
  selector:
    name: fileserver-pod
    app: bale-app
  ports:
  - port: 8000
    targetPort: 8000
