apiVersion: v1
kind: Service
metadata:
  name: fileserver-service
  labels:
    name: fileserver-service-nodeport
    app: bale-app
spec:
  type: NodePort
  selector:
    name: fileserver-pod
    app: bale-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001

